name: Secrets check

on:
  push:

jobs:
  runs-on: ubnutu-latest

  steps:
    - name: Show Scerets Usage
      env: 
        APP_ENV: ${{ secrets.APP_ENV }}
      run: |
        echo "Application Environment Loaded"

